# Site settings
title: NegraTec
email: negratec@gmail.com
description: Algo

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://negratec.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: ""
data-ad-client: ""
google_ad_client: "" 

google_analytics: ""
addthis_id: ""
disqus_account: "" 

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/negratec
  - title: facebook
    url: https://facebook.com/negratec
  - title: github
    url: http://github.com/NegraTec

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
